---
title: "No title yet"
author: "Malte Ruehlemann"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
---



# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev='pdf',
               fig.height = 5,
               fig.width = 4 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 18))

# Set seed for reproducibility
set.seed(222)
```


## Load libraries for the session

```{r}
library(ggplot2)
library(tidyverse)
library(cowplot)

```

## Import data
```{r}
marine_all_out = readRDS("output_data/marine.all_out.Rds")
hmpgut_all_out = readRDS("output_data/hmpgut.all_out.Rds")

color_frame=data.frame(group=c("CONCOCT","GSA2k","MaxBin2","MAGScoT","MetaBAT2","metaWRAP","VAMB","DASTool"), color=RColorBrewer::brewer.pal(n = 8, name="Paired"))
```

# Marine dataset = synthetic dataset from CAMI challange

## Runtimes

```{r}
timeplot1 = marine_all_out$timelogs %>% group_by(pipe, step, step_this) %>%  filter(!pipe %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% summarise(mean_time_in_m = mean(time_in_s)/60, total_time_in_m = sum(time_in_s)) %>% mutate(step=gsub("_AB|_CD","",step), part=ifelse(grepl("hmm|prod", step),"Preprocessing","Core Algorithm")) %>% ggplot(aes(x=pipe, y=mean_time_in_m, fill=part)) + geom_col(col="black") + scale_fill_brewer(palette = "Paired") + ylab("Mean Runtime (min)") + scale_x_discrete(labels=c("MAGScoT","DASTool","metaWRAP")) + scale_y_continuous(expand=c(0,0), limits=c(0,450)) + theme(legend.position = "bottom", axis.text.x = element_text(angle=45, hjust=1)) + xlab("")

marine_all_out$timelogs %>% group_by(pipe) %>% summarize(sum=sum(time_in_s)/60, mean=mean(time_in_s)/60, n=n())
```

## Output

### Total

```{r}
library(cowplot)
# bind_rows(marine_all_out$all_amber %>% mutate(scorebase = "amber") %>% filter(Bin.size..bp.>=250000) %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.ID)),
#           marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)),
#           marine_all_out$all_bisco %>% mutate(scorebase = "biscoreto") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(bin))) %>%
plot1= marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>%  mutate(set=gsub("bisocreto","biscoreto",set), set=gsub("DASTool","dastool",set))%>%  filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% mutate(type=ifelse(set %in% c("concoct", "maxbin2", "metabat2", "vamb"), "single", "ensemble")) %>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set)) %>%
  ggplot(aes(x=bin_rank, y=score, col=set)) + geom_line(size=1, aes(lty=type)) + coord_cartesian(ylim=c(0.5,1), xlim=c(0,750), expand = 0) + geom_hline(yintercept = c(0.5,0.7,0.9), col="lightgrey", lty=2) + scale_color_manual(values = color_frame$color, breaks=color_frame$group) + theme(legend.position = "none")  + xlab("Bin Rank") + ylab("Score")


p1 =  marine_all_out$all_checkm %>% group_by(set) %>% mutate(set=gsub("DASTool","dastool", set)) %>% filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set))  %>% arrange(score) %>% summarise(completeness = median(completeness), contamination = median(contamination),  n=n()) %>% ggplot(aes(x=1-contamination, y=completeness, fill=set)) + geom_point(aes(size=n), shape=21, alpha=.8) + geom_hline(yintercept = 0.9, lty=2, col="lightgrey")+ geom_vline(xintercept = 0.9, lty=2, col="lightgrey") + coord_cartesian(xlim = c(.75,1), ylim=c(0,1), expand = c(0)) + theme(legend.position = "none") + scale_fill_manual(values = color_frame$color, breaks=color_frame$group) + scale_size_continuous(range=c(4,6))  + scale_y_continuous(labels = scales::percent) + scale_x_continuous(labels = scales::percent, breaks=c(.8,.9,1)) + xlab("1 - Contamination") + ylab("Completeness")

p2 = marine_all_out$all_checkm %>% group_by(set) %>% mutate(set=gsub("DASTool","dastool", set)) %>% filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set)) %>% arrange(score) %>% ggplot(aes(y=completeness, x=set, fill=set)) + geom_boxplot(outlier.size = .5) +  scale_y_continuous(position = "right", expand = c(0,0)) + theme(axis.text.x = element_blank()) + scale_x_discrete(position = "top", expand = c(0,0)) + theme_nothing() + scale_fill_manual(values = color_frame$color, breaks=color_frame$group)

p3 = marine_all_out$all_checkm %>% group_by(set)  %>% mutate(set=gsub("DASTool","dastool", set)) %>% filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set))  %>% arrange(score) %>% ggplot(aes(x=1-contamination, y=set, fill=set)) + geom_boxplot(outlier.size = 0.5) + scale_x_continuous(expand = c(0,0))  + coord_cartesian(xlim = c(.75,1), expand = c(0)) + theme_nothing() + scale_fill_manual(values = color_frame$color, breaks=color_frame$group)

align_plots(p1 + theme(legend.position = "none"), p2,  p3, ncol=2, align = "hv", axis ="tblr", rel_widths = c(.7,.3))

aa=align_plots(p1 ,p2, plot1, timeplot1 + theme(legend.position = "none"), align="h")
ab=align_plots(aa[[1]] , p3, align="v")



plot_grid(aa[[3]], plot2, ncol=2)

```


```{r}
left_join(
marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .9, contamination<0.05) %>% summarise(n_90_5=n()),
marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .9, contamination<0.10) %>% summarise(n_90_10=n())) %>% left_join(

left_join(
marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .7, contamination<0.05) %>% summarise(n_70_5=n()),
marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .7, contamination<0.10) %>% summarise(n_70_10=n()))) %>% left_join(

left_join(
marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .5, contamination<0.05) %>% summarise(n_50_5=n()),
marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .5, contamination<0.10) %>% summarise(n_50_10=n()))) %>% left_join(marine_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .5, contamination<0.10, score>0.5) %>% summarise(n_score50=n()) )


```

# HMP Gut dataset = 50 random gut metagenomes

## Runtimes

```{r}
timeplot2=hmpgut_all_out$timelogs  %>% group_by(pipe, step, step_this) %>%  filter(!pipe %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% summarise(mean_time_in_m = mean(time_in_s)/60, total_time_in_m = sum(time_in_s)) %>% mutate(step=gsub("_AB|_CD","",step), part=ifelse(grepl("hmm|prod", step),"Preprocessing","Core Algorithm")) %>% ggplot(aes(x=pipe, y=mean_time_in_m, fill=part)) + geom_col(col="black") + scale_fill_brewer(palette = "Paired") + ylab("Mean Runtime (min)") + scale_x_discrete(labels=c("BiScoReTo","DASTool","metaWRAP")) + scale_y_continuous(expand=c(0,0), limits=c(0,125)) + theme(legend.position = "bottom", axis.text.x = element_text(angle=45, hjust=1)) + xlab("")

hmpgut_all_out$timelogs %>% group_by(pipe) %>% summarize(sum=sum(time_in_s)/60, mean=mean(time_in_s)/60, n=n())
```


## Output

### Total

```{r}
# bind_rows(hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)),
#           hmpgut_all_out$all_bisco %>% mutate(scorebase = "biscoreto") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(bin))) %>%

plot_hmp1=hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% mutate(set=gsub("bisocreto","biscoreto",set), set=gsub("DASTool","dastool",set))%>%  filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% mutate(type=ifelse(set %in% c("concoct", "maxbin2", "metabat2", "vamb"), "single", "ensemble")) %>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set)) %>%
  ggplot(aes(x=bin_rank, y=score, col=set)) + geom_line(size=1, aes(lty=type)) + coord_cartesian(ylim=c(0.5,1), xlim=c(0,520), expand = 0) + geom_hline(yintercept = c(0.5,0.7,0.9), col="lightgrey", lty=2)+ scale_color_manual(values = color_frame$color, breaks=color_frame$group)  + theme(legend.position = "none") + xlab("Bin Rank") + ylab("Score")


ph1 =  hmpgut_all_out$all_checkm %>% group_by(set) %>% mutate(set=gsub("DASTool","dastool", set)) %>% filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard"))%>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set))  %>% arrange(score) %>% summarise(completeness = median(completeness), contamination = median(contamination),  n=n()) %>% ggplot(aes(x=1-contamination, y=completeness, fill=set)) + geom_point(aes(size=n), shape=21, alpha=.8) + geom_hline(yintercept = 0.9, lty=2, col="lightgrey")+ geom_vline(xintercept = 0.9, lty=2, col="lightgrey") + coord_cartesian(xlim = c(.75,1), ylim=c(0,1), expand = c(0)) + theme(legend.position = "none") + scale_fill_manual(values = color_frame$color, breaks=color_frame$group) + scale_size_continuous(range=c(4,6)) + scale_y_continuous(labels = scales::percent) + scale_x_continuous(labels = scales::percent, breaks=c(.8,.9,1)) + xlab("1 - Contamination") + ylab("Completeness")

ph2 = hmpgut_all_out$all_checkm %>% group_by(set) %>% mutate(set=gsub("DASTool","dastool", set)) %>% filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set)) %>% arrange(score) %>% ggplot(aes(y=completeness, x=set, fill=set)) + geom_boxplot(outlier.size = .5) +  scale_y_continuous(position = "right", expand = c(0,0)) + theme(axis.text.x = element_blank()) + scale_x_discrete(position = "top", expand = c(0,0)) + theme_nothing() + scale_fill_manual(values = color_frame$color, breaks=color_frame$group)

ph3 = hmpgut_all_out$all_checkm %>% group_by(set)  %>% mutate(set=gsub("DASTool","dastool", set)) %>% filter(!set %in% c("biscoreto_ms50", "biscoreto_nomerge", "Gold standard")) %>% mutate(set = gsub("concoct","CONCOCT", set), set = gsub("maxbin2","MaxBin2", set), set = gsub("metabat2","MetaBAT2", set) ,set = gsub("biscoreto_ms80","BiScoReTo", set) , set = gsub("gsa2k","GSA2k", set), set = gsub("vamb","VAMB", set), set = gsub("metawrap","metaWRAP", set) , set = gsub("dastool","DASTool", set)) %>% arrange(score) %>% ggplot(aes(x=1-contamination, y=set, fill=set)) + geom_boxplot(outlier.size = 0.5) + scale_x_continuous(expand = c(0,0))  + coord_cartesian(xlim = c(.75,1), expand = c(0)) + theme_nothing() + scale_fill_manual(values = color_frame$color, breaks=color_frame$group)

align_plots(p1 + theme(legend.position = "none"), p2,  p3, ncol=2, align = "hv", axis ="tblr", rel_widths = c(.7,.3))

ba=align_plots(ph1+xlab("") , ph2, plot_hmp1 +xlab("") , timeplot2 + theme(legend.position = "none"), align="h")
bb=align_plots(ba[[1]] , ph3, align="v")


plot_grid(get_legend(p1 + guides(size="none") + theme(legend.position = "bottom", legend.title = element_blank())), NULL, ab[[1]], aa[[2]], ab[[2]],  NULL, rel_widths = c(.8,.15), rel_heights = c(.1, .7,.1), ncol=2)


summary_plot=plot_grid(
    plot_grid(NULL, NULL, ab[[2]],  NULL, aa[[4]], aa[[3]], ab[[1]], aa[[2]], rel_widths = c(0.2, 0.3,0.35,.08), rel_heights = c(.15,.7), ncol=4),
    plot_grid(NULL, get_legend(plot1 + guides(size="none", color="none") + theme(legend.position = "bottom", legend.title = element_blank())), bb[[2]],  NULL,ba[[4]], ba[[3]], bb[[1]], ba[[2]],  rel_widths = c(0.2, 0.3,0.35,.08), rel_heights = c(.15,.7), ncol=4),
     get_legend(plot1 + guides(size="none", lty="none") + theme(legend.position = "bottom", legend.title = element_blank())),
    ncol=1, rel_heights = c(.45,.42,.08), labels = c("A","B"))





ggsave(filename = "summary_plot.png", summary_plot, height=10, width=10)

```


```{r}
left_join(
hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .9, contamination<0.05) %>% summarise(n_90_5=n()),
hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .9, contamination<0.10) %>% summarise(n_90_10=n())) %>% left_join(

left_join(
hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .7, contamination<0.05) %>% summarise(n_70_5=n()),
hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .7, contamination<0.10) %>% summarise(n_70_10=n()))) %>% left_join(

left_join(
hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .5, contamination<0.05) %>% summarise(n_50_5=n()),
hmpgut_all_out$all_checkm %>% mutate(scorebase = "checkm") %>% group_by(set) %>% arrange(-score) %>% mutate(bin_rank = seq_along(Bin.Id)) %>% filter(completeness > .5, contamination<0.10) %>% summarise(n_50_10=n())))
```


```{r}
hmpgut_all_out$all_counts %>% group_by(feature) %>% summarise(sum=sum(count), mean=mean(count))

```


```{r}
lapply(names(hmpgut_all_out), function(n) write.table(hmpgut_all_out[[n]], paste0("tables/hmpgut.",n,".tsv", sep="\t")))
lapply(names(marine_all_out), function(n) write.table(marine_all_out[[n]], paste0("tables/marine.",n,".tsv", sep="\t")))
```





# Session information

```{r}
sessionInfo()
```
